#!/bin/bash
echo "OPENCV_VERSION=${OPENCV_VERSION}"
echo "OPENCV_URL=${OPENCV_URL}"
echo "ENABLE_CONTRIB=${ENABLE_CONTRIB}"
echo "FORWARD_CONTRIB=${FORWARD_CONTRIB}"
echo "FORCE_BUILD=${FORCE_BUILD}"
echo "TMP=${TMP}"
echo "TAR_INDEX_URL=${TAR_INDEX_URL}"